name: Go
on: [push]
env:
  GO111MODULE: "off"
  GOOS: "linux"
  GOARCH: "amd64"
  REPO_NAME: github.com/${{ github.repository }}
  PKG_PACKER_TARGET: ${{ github.workspace }}/build/amd64/pkg-packer
  PKG_PACKER_SOURCE: pkg_packer/cmd/pkg_packer

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set environment on build
        run: |
          echo ::set-env name=GOPATH::${HOME}/go

      - name: Setup GO build environment
        run: |
          mkdir -p $(dirname ${GOPATH}/src/${REPO_NAME})
          ln -svf ${{ github.workspace }} ${GOPATH}/src/${REPO_NAME}

      # build and run using only vendor packages to build in the private network
      - name: Test
        run: |
          cd $GOPATH/src/$REPO_NAME
          go fmt $(go list ./... | grep -v /vendor/)
          go vet $(go list ./... | grep -v /vendor/)
          go test -race $(go list ./... | grep -v /vendor/)

      - name: Build-amd64
        run: |
          go build -v -ldflags "-extldflags '-static'" -o ${PKG_PACKER_TARGET} ${PKG_PACKER_SOURCE}
